service: api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-southeast-2:362928302509:table/subscriptionsTable'

plugins:
  - serverless-jetpack

package:
  individually: true

custom:
  jetpack:
    preInclude:
      - '!**'

    base: dist

    roots:
      - .
      - ../../

    concurrency: 8

    trace:
      dynamic:
        resolutions:
          'pkginfo/lib/pkginfo.js': ['../../package.json']

functions:
  connectionHandler:
    handler: dist/handler.connectionHandler
    events:
      - websocket: $connect
      - websocket: $disconnect
    environment:
      WS_URL: ${cf:api-dev.ServiceEndpointWebsocket}
  subscriptionHandler:
    handler: dist/handler.subscriptionHandler
    events:
      - websocket: subscribe
      - websocket: unsubscribe
    environment:
      WS_URL: ${cf:api-dev.ServiceEndpointWebsocket}
  streamHandler:
    handler: dist/handler.streamHandler
    timeout: 60
    events:
      - stream:
          type: kinesis
          arn: arn:aws:kinesis:ap-southeast-2:362928302509:stream/data-stream-demo
          consumer: true
    environment:
      WS_URL: ${cf:api-dev.ServiceEndpointWebsocket}
  defaultHandler:
    handler: dist/handler.defaultHandler
    events:
      - websocket: $default

resources:
  Resources:
    subscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: subscriptionsTable
        AttributeDefinitions:
          - AttributeName: subscriptionId
            AttributeType: S
        KeySchema:
          - AttributeName: subscriptionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
